### ISSUE TITLE
New difficulty adjustment algorithm

### ISSUE THREAD

**Issue by ghost** [xun-project/UltraNote#7]
Current algorithm is zawy's LWMA.
  Diff Window = `60`

#### PoW issue to consider:
Pools take block templates right after a block was added to block-chain and keep the block until the block is solved. This behavior leads to various lags:

1. Block template's `timestamp` is assigned from `actual clock time`, the time difference between when it was taken by the pool  and when it was solved isn't considered by difficulty algorithms. 
2. In small networks (1-3 pools) every 2nd block would get a time lag (very small time difference compare to prev. block). _Example: 1) Pool takes first block and solves it 2 minutes [12:00:00 am] 2) the second block template is taken 2 minutes after [12:02:00 am] 3) The second block is solved [12:02:00am] 3) Third block template is taken [ !! 12:02:10 am !! ] 4) Third block is solved [ !! 12:02:10 am !! ]   5) Fourth template will be taken at current clock time, say [12:05:00 am], and from this point every second block will have a time lag._
For larger networks this time lag would be somewhat around propagation time in network (usually pretty fast). 
3. This issue also affects transaction confirmation time. Because some block templates taken in matter of seconds won't include most transactions appeared in tx pool at current block-chain height. So the transaction confirmation time would be shifted +1 block.

--------------------------------------------------------------------------
Previous algorithm was applied from [Sumokoin's Work](https://github.com/sumoprojects/sumokoin/pull/10)
Formula can be found in [zawy12's work](https://github.com/zawy12/difficulty-algorithms/issues/9)
  Diff Window = `35`

#### Leads
[KARBOwanec's Disscussion](https://github.com/seredat/karbowanec/commit/231db5270acb2e673a641a1800be910ce345668a)
[KARBOwanec's reward adjustment algorithm](https://github.com/seredat/karbowanec/commit/231db5270acb2e673a641a1800be910ce345668a#commitcomment-24037066)

[zawy12's comment on timestamp limits ](https://github.com/seredat/karbowanec/commit/231db5270acb2e673a641a1800be910ce345668a#commitcomment-23754108)
[zawy12's (Gandalf's difficulty algorithm)](https://github.com/seredat/karbowanec/commit/231db5270acb2e673a641a1800be910ce345668a#commitcomment-23754431)

*Ideas:*
<details>
#### IDEA 1: _Increase reward penalty for time-warped blocks_
T = penalty target time
S = timespan ( `current.timestamp - tail.timestamp` )

Simple: 
```
if S < T
  PENALTY = 1 - S / T
else
  PENALTY = 0
```

[Test #1, `T = Diff Target Time * 0.7`](https://github.com/xun-project/UltraNote/commit/b1252888d14cf222d58356f504a53ddbb5369dfc)
- Requires changing current Reward function to redistribute penalties on next (n) blocks.

#### IDEA 2: _Add public key authentication for trusted pools_ (extreme measure) 
In that case next block version should carry a hash generated from a private key. Blocks would add only if hash is verifiable against public key.
- Maybe a good idea for new  coins for start period. Or maybe best to use PoW alternatives

#### IDEA 3: _Keep solved blocks until `diff target time >=  adjust value`, then pick trusted one_.
- It would require new logic whenever new block should append to blockchain
- Hard to implement on mainnet with legacy code
- Need methods of calculating `trust score` and `adjust value`. 
- Possible it can delay transaction confirmation
- Consensus: Not compatible with PoW. 

#### IDEA 4: _Enforce time limits_
- Requires modification of pool software
- Messes with PoW

#### IDEA 5: _ Fare rewards_ (@cheebeez)
It may be achievable.
Assuming that the longer block was solving the more effort  miners put to find it.
- Opens possibility to manipulate by reward amount.
- Great idea. Worth to test.
</details>

**Comment by cheebeez** [comment]
IDEA 4: Just fair reward.
If effort 70% -> reward -30%
If effort 200% -> reward + 100%

**Comment by zawy12** [comment]
If you hard fork again, you might want to use my [new algorithm LWMA](https://github.com/zawy12/difficulty-algorithms/issues/3).  Nine monero clones are using it.  

I got Sumokoin going down the wrong path when they used medians.  After more testing, I decided the medians was not good, but they were already committed to it.  Also, selecting N=17 for them was a bad idea.  It looks like you're now using N=35 which is a lot better, but it still probably accidentally swings up and down too much.

**Comment by UltraNote** [comment]
Thank you @zawy12 We will make sure to implemet this algo in our next hard fork.

**Comment by zawy12** [comment]
As I said above, the N=35 with a simple moving average should work fine.  But someone has figured out how to send your difficulty really low.  I can't determine how they are doing it because they are not using bad timestamps.  Your difficulty is dropping even after the attack has been on for 35 blocks  It should have jumped up 1000% if it were a simple moving average.  The only thing I can guess is that "cut" is causing your difficulty to not act like a simple moving average.  

![image](https://user-images.githubusercontent.com/18004719/38781859-93835302-40b9-11e8-970e-fd6839fcdbb4.png)

**Comment by nesterow** [comment]
Hi @zawy12 . Are those graphs from XUN?  XUN forked from block 34147, before this block it was using legacy difficulty algorithm. After we forked the difficulty dropped significantly. After fork I monitored network for month and didn't see such changes even when hashrate on pools suddenly raised from 150kh to 1,5mh and dropped back . Maybe something changed for this time.

**Comment by nesterow** [comment]
#### PoW issue to consider:
Pools take block templates right after a block was added to block-chain and keep the block until the block is solved. This behavior leads to various lags:

1. Block template's `timestamp` is assigned from `actual clock time`, the time difference between when it was taken by the pool  and when it was solved isn't considered by difficulty algorithms. 
2. In small networks (1-3 pools) every 2nd block would get a time lag (very small time difference compare to prev. block). _Example: 1) Pool takes first block and solves it 2 minutes [12:00:00 am] 2) the second block template is taken 2 minutes after [12:02:00 am] 3) The second block is solved [12:02:00am] 3) Third block template is taken [ !! 12:02:10 am !! ] 4) Third block is solved [ !! 12:02:10 am !! ]   5) Fourth template will be taken at current clock time, say [12:05:00 am], and from this point every second block will have a time lag._
For larger networks this time lag would be somewhat around propagation time in network (usually pretty fast). 
3. This issue also affects transaction confirmation time. Because some block templates taken in matter of seconds won't include most transactions appeared in tx pool at current block-chain height. So the transaction confirmation time would be shifted +1 block.

**Comment by UltraNote** [comment]
Solved in UltraNote node version 1.0.7.
Using Zawy difficulty algo LWMA-2 and CryptoNote-Lite V1

**Comment by zawy12** [comment]
In the master I only see LWMA, not LWMA-2
